source :rubygems
gem 'unicorn',            '~> 1.1.2'
gem 'rack',               '~> 1.2.1'
gem 'activesupport',      '~> 3.0.0.rc2'
gem 'sinatra',            '~> 1.0'
gem 'sinatra-reloader',   '~> 0.5.0'
gem 'directory_watcher',  '~> 1.3.2'
gem 'backports'
gem 'haml'
gem 'shotgun'
